### ISSUE TITLE
Thesis in English ?

### ISSUE THREAD

**Issue by balaji-ch** [cdalamagkas/XGPON_Simulator#1]
Hi Christos,

Is your thesis titled 'Design of Market Mechanism for Dynamic Bandwidth Allocation on XG-PON' available in English ?

**Comment by Mrzong1999** [comment]
Hi Christos,

can i learn your paper ?

**Comment by cdalamagkas** [comment]
> Hi Christos,
> 
> Is your thesis titled 'Design of Market Mechanism for Dynamic Bandwidth Allocation on XG-PON' available in English ?

Unfortunately, the thesis is only in Greek.

**Comment by cdalamagkas** [comment]
> Hi Christos,
> 
> can i learn your paper ?

The paper is the following: 

C. Dalamagkas, P. Sarigiannidis, I. Moscholios, T. D. Lagkas, and M. Obaidat, “PAS: A Fair Game-Driven DBA Scheme for XG-PON Systems,” 2018 11th International Symposium on Communication Systems, Networks &amp; Digital Signal Processing (CSNDSP). IEEE, Jul. 2018. doi: 10.1109/csndsp.2018.8471787.
